### PR TITLE
[WIP] test: setup Integration testing architecture and add accounts & trading tests

### PR DESCRIPTION
**Pull request by willyspinner**
Closes story #31 .

### CODE REVIEW

**Comment by willyspinner** [comment]
NOTE: integration testing architecture is set up and trading routes fully tested so far.

We need to do accounts testing and this can merge.

I found a db pool exhaustion bug in the user `/api/accounts/register`. We didn't release the DB pool client there, which is bad -  sidenote - I wonder if there's a good way to automate this -

**Comment by willyspinner** [comment]
^ this is ready to be merged, just need to wait out tests.

**Comment by willyspinner** [comment]
@akanksha003  would you mind reviewing?

**Review by akanksha003 — APPROVED** [review]
Nice!

**Pull request merged**
