### PR TITLE
use separate server and client dirs (project structure)

### LINKED ISSUE #28: [BUG] - Eliminate dual `package.json` structure
## Description
we seem to have some confusion with the `package.json` files. Need to change it so that we can use only one package.json for frontend and backend.

NOTE: let's do this after the stories to add authentication & buy sell feature frontends are setup. Makes it easier.

Also, every frontend stakeholder needs to review and approve this. 
## Steps to Reproduce
look at our repo structure :) 

## Expected Behavior
Give a clear and concise description of what should be the expected behavior.

## Additional Context
Enter any other details such as dependencies, environment, examples, etc.

## Relevant screenshots
If applicable, add screenshots to help illustrate the bug.

### PR DESCRIPTION
**Pull request by willyspinner**
closes #28. We decide to separate the client and the server into their own separate folders.

### CODE REVIEW

**Comment by willyspinner** [comment]
Major changes I made:

- cleaned up `README.md` to include actual commands used to get set up with the project
- moved server files to a `./server/` directory
- add package.json in root directory used to run both client and backend at the same time
- Moved frontend dependencies to `./client/package.json`
- Changed CI & deploy scripts to reflect this refactoring

## Things to note

1. Running `npm install` in project root will install both client and backend dependencies in their own respective folders
2. Running `npm start` in project root will run bot hclient and backend at the same time. See root `package.json` for more details

**Comment by willyspinner** [comment]
Root directory looks like this now, much cleaner than before:
Screen Shot 2021-02-18 at 9 39 51 PM

**Comment by akanksha003** [comment]
Noice! This is nice change from what we currently have. Thanks for fixing this issue.

**Review by akanksha003 — APPROVED** [review]
Reviewed

**Review by varun1729 — APPROVED** [review]
Some of the best work I have ever seen. Congratulations! Pleasure to approve

**Review by SeunghyunDKim — APPROVED** [review]

**Review by ChoiJ0527 — APPROVED** [review]
Looks good! Thanks for cleaning this up for us.

**Pull request merged**
