### PR TITLE
Ci/add cicd

### PR DESCRIPTION
**Pull request by willyspinner**
Task of story #5. 

NOTE that the master branch already has a first version of `.travis.yml` cicd file, which is a mistake. The introduction of CICD should be done in this PR, but oh well, too late.

 TODO: add on: master branch deploy protection

### CODE REVIEW

**Comment by willyspinner** [comment]
What we need to do now is to add the deploy script or travis CI deploy configurations to deploy to our cloud environment of choice.

For AWS EB (Elastic Beanstalk), follow [this tutorial](https://docs.travis-ci.com/user/deployment/elasticbeanstalk/)  to change the `.travis.yml file`.

This task is blocked until story #7  is finished (cloud environment set up). We need to weigh in pros and cons of using EB, EC2, or even other providers like DigitalOcean. 

I would prefer using EB since the travis configuration seems quite doable, rather than manually configuring `ssh`-ing the bundle into the server, restarting the node process, etc.

**Comment by varun1729** [comment]
Thanks Wilson for getting this started. I will work on unblocking #7 :)

**Comment by willyspinner** [comment]
I tried doing deployments on my EB instance but couldnt get it to work xD

My encrypted aws keys apparently not found

**Comment by willyspinner** [comment]
Closing in favor of new PR #11

**Pull request closed without merging**
