### PR TITLE
Watchlist portfolio

### LINKED ISSUE #45: add Watchlist + portfolio on chart page
## User Story
As a user, I would like to have my watchlist and portfolio handy when looking / buying stocks in chart page.

## Detailed Description
As discussed, we want to put the watchlist and portfolio in the same place at the chart page, which is directly below the stock chart.

We also need to show the balance of remaining funds and stocks owned in the chart page (in the buy and sell widget or below it - TBD).

There will be a frontend and backend component for this:
- Backend needs to implement the watchlist (like) feature for each stock - Get, add and remove. 
- Frontend will need to create a tabbed view that has an option to select watchlist or portfolio in chart page.

## Subtasks (Please also link task PRs here)
All will be done in 1 PR
- [x] Backend - Add temporary portfolio value for each item (hardcoded)
- [x] Backend - Add PG table for watchlist
- [x] Backend - Add watchlist routes (Get, Add & Remove)
- [x] Frontend - create watchlist component with watchlist service
- [x] Frontend - add tab to navigate between portfolio & watchlist in chart page

### PR DESCRIPTION
**Pull request by willyspinner**
Closes #45

### CODE REVIEW

**Comment by willyspinner** [comment]
I'm finished, this is ready to be reviewed.

**Review by akanksha003 — APPROVED** [review]
Hey I think this looks good. We can merge it now 👌

**Review by akanksha003 — APPROVED** [review]
Thanks for resolving those conflicts! 
Let the merging begin 😁

**Review by willyspinner — COMMENTED** [review]
OK!

**Pull request merged**
